### PR TITLE
Deal with __getstate__ and __setstate__ methods

### LINKED ISSUE #583: Audit __getstate__ and __setstate__ methods
There are a number of Chaco classes which override `__getstate__` and possibly `__setstate__`.  Most of these seem to be removing traits from the state dict, which is now correctly handled by marking those traits as `transient`.

For example:

https://github.com/enthought/chaco/blob/e3423614d654a203bd82ee087c085abe13b465b1/chaco/lineplot.py#L415-L421

This is removing the `traits_view` trait from the state - under normal Traits, this will never be in the state because of special handling of Views, so this whole method can be removed.

Another example:

https://github.com/enthought/chaco/blob/e3423614d654a203bd82ee087c085abe13b465b1/chaco/grid.py#L413-L419

Here the traits `_cache_valid`, `_tick_list`, `_tick_positions`, `_tick_extents` are being removed from the state.  These traits should be marked with `transient=True` metadata and then the `__getstate__` method can be removed.

If it turns out that there are necessary things being done in a `__getstate__`, we should make sure that there is a `super` call.

### PR DESCRIPTION
**Pull request by aaronayres35**
closes #583 

This PR rermoves uses of the `__getstate__` method when it is not needed, and cleans up its use where it is.

The `__setstate__` methods can be dealt with in a follow up PR

### CODE REVIEW

File: chaco/abstract_mapper.py [hunk 1]
```diff
@@ -49,13 +49,6 @@ def map_data_array(self, screen_vals):
     # ------------------------------------------------------------------------
     # Persistence-related methods
     # ------------------------------------------------------------------------
-    def __getstate__(self):
-        state = super(AbstractMapper, self).__getstate__()
-        for key in ["_cache_valid"]:
```
Comment (aaronayres35) [inline chaco/abstract_mapper.py:54]: `_cache_valid` is not a trait on this class or any of its base classes

File: chaco/tools/simple_zoom.py [hunk 2]
```diff
@@ -70,25 +70,25 @@ class SimpleZoom(AbstractOverlay, ToolHistoryMixin, BaseZoomTool):
...
-    minimum_screen_delta = Int(10)
+    minimum_screen_delta = Int(10, transient=True)
 
     # -------------------------------------------------------------------------
     # Appearance properties (for Box mode)
     # -------------------------------------------------------------------------
 
     # The pointer to use when drawing a zoom box.
-    pointer = "magnifier"
+    pointer = Str("magnifier", transient=True)
```
Comment (aaronayres35) [inline chaco/tools/simple_zoom.py:91]: This may be bad if `pointer` is meant to be a class attribute, similar to `stack_index` in `plot_container.py`.

I need to climb up the class hierarchy to see if it was previously defined as a trait.  I remember Kit mentioning this being a point of confusion.  I am not sure what the ideal way to avoid this confusion would be (aside from maybe a comment above saying if this is a class attribute or just setting a trait to a value.  I guess if setting a trait to some value, you could do as I have done here? and explicitly do something like `Str(___)`

File: chaco/tests/test_arraydatasource.py [hunk 3]
```diff
@@ -247,7 +254,7 @@ def test_serialization_state_no_persist(self):
             "_min_index",
             "_max_index",
         ]:
-            self.assertIn(key, state)
+            self.assertNotIn(key, state)
```
Comment (aaronayres35) [inline chaco/tests/test_arraydatasource.py:257]: If not persisting they should not be in state, but if we are they should be. I believe these tests are doing what they are supposed to now

File: chaco/tools/simple_zoom.py (hunk 2 above)
Comment (aaronayres35) [reply chaco/tools/simple_zoom.py:91]: As a quick sanity check, on master I defined a class attribute `thing = "A"` on `SimpleZoom`.  I then ran:
```
from chaco.tools.simple_zoom import SimpleZoom
SimpleZoom.thing  # I see 'A' printed
SimpleZoom.pointer  # I get an error "type object 'SimpleZoom' has no attribute 'pointer'"
```

So, I believe the change made here is the right one

File: chaco/plot_containers.py [hunk 4]
```diff
@@ -281,9 +281,8 @@ def _do_stack_layout(self, components, align):
     # PICKLE FIXME: blocked with _pickles, but not sure that was correct.
     def __getstate__(self):
         state = super(StackedPlotContainer, self).__getstate__()
-        for key in ["stack_dimension", "other_dimension", "stack_index"]:
-            if key in state:
-                del state[key]
+        if "stack_index" in state:
+            del state["stack_index"]
```
Comment (aaronayres35) [inline chaco/plot_containers.py:285]: stack_index is a class attribute not a trait, so I believe this is still needed

File: chaco/abstract_mapper.py (hunk 1 above)
Comment (rahulporuri) [reply chaco/abstract_mapper.py:54]: sigh. but it is a trait on the subclasses e.g. `Base1DMapper`

File: chaco/lineplot.py [hunk 5]
```diff
@@ -449,14 +449,6 @@ def _line_width_changed(self):
         self.invalidate_draw()
         self.request_redraw()
 
-    def __getstate__(self):
-        state = super(LinePlot, self).__getstate__()
-        for key in ["traits_view"]:
```
Comment (rahulporuri) [inline chaco/lineplot.py:454]: Is `traits_view` a transient trait? I dont see anything in the code or in the documentation saying that it is.

File: chaco/tools/simple_zoom.py [hunk 6]
```diff
@@ -647,28 +647,3 @@ def _next_state_pressed(self):
...
-        dont_pickle = [
-            "always_on",
-            "always_on_modifier",
-            "enter_zoom_key",
-            "exit_zoom_key",
-            "minimum_screen_delta",
-            "event_state",
-            "reset_zoom_key",
-            "prev_zoom_key",
-            "next_zoom_key",
```
Comment (rahulporuri) [inline chaco/tools/simple_zoom.py:663]: im not sure where these traits were being magically defined

**Review by rahulporuri — APPROVED** [review]
LGTM with a couple of comments

File: chaco/lineplot.py (hunk 5 above)
Comment (aaronayres35) [reply chaco/lineplot.py:454]: I was going off wha Corran said in this issue description: "This is removing the traits_view trait from the state - under normal Traits, this will never be in the state because of special handling of Views, so this whole method can be removed."
This should certainly be documented though

File: chaco/tools/simple_zoom.py (hunk 6 above)
Comment (aaronayres35) [reply chaco/tools/simple_zoom.py:663]: me either, this is the only place I was seeing them in the codebase. Perhaps they once existed but had been removed

File: chaco/abstract_mapper.py (hunk 1 above)
Comment (aaronayres35) [reply chaco/abstract_mapper.py:54]: Ah you are right.  TBH I believe that all related traits should be transient even if they weren't perviously involved in a `__getstate__`method.  For example other classes have `_screen_cache_valid` or `_selection_cache_valid` traits.  I think I will update all of these to be transient as I can't see why they shouldn't all be so

**Comment by aaronayres35** [comment]
Looks like the CI failure on windows/pyqt from the test introduced by #636 is reproducible on every PR except the original (no idea how it didn't fail on 636).
```
======================================================================
ERROR: test_dont_crash_on_click (chaco.tests.test_plot.TestEmptyPlot)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\chaco\chaco\.edm\envs\chaco-test-3.6-pyqt\lib\site-packages\chaco\tests\test_plot.py", line 134, in test_dont_crash_on_click
    [(1, 1), (25, 25), (50, 50), (100, 100)],
  File "D:\a\chaco\chaco\.edm\envs\chaco-test-3.6-pyqt\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "D:\a\chaco\chaco\.edm\envs\chaco-test-3.6-pyqt\lib\site-packages\traitsui\testing\tester\ui_tester.py", line 106, in create_ui
    process_cascade_events()
  File "D:\a\chaco\chaco\.edm\envs\chaco-test-3.6-pyqt\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "D:\a\chaco\chaco\.edm\envs\chaco-test-3.6-pyqt\lib\site-packages\traitsui\testing\_exception_handling.py", line 74, in reraise_exceptions
    raise RuntimeError(msg)
RuntimeError: Uncaught exceptions found.
=== Exception (type: <class 'AttributeError'>, value: '_QtWindow' object has no attribute 'handler') ===
Traceback (most recent call last):
  File "D:\a\chaco\chaco\.edm\envs\chaco-test-3.6-pyqt\lib\site-packages\enable\qt4\base_window.py", line 258, in leaveEvent
    self.handler.leaveEvent(event)
AttributeError: '_QtWindow' object has no attribute 'handler'
```

I also find the error quite confusing, as looking in enable, the `_QtWindow` class clearly has `self.handler = _QtWindowHandler(self, enable_window)` in its `__init__` method... Also this seems like a very strange thing to be windows specific... 🤔 
I will look into this more

File: chaco/base_contour_plot.py [hunk 7]
```diff
@@ -54,10 +54,10 @@ class BaseContourPlot(Base2DPlot):
     # ------------------------------------------------------------------------
 
     # Is the cached level data valid?
-    _level_cache_valid = Bool(False)
+    _level_cache_valid = Bool(False, transient=True)
 
     # Is the cached color data valid?
-    _colors_cache_valid = Bool(False)
+    _colors_cache_valid = Bool(False, transient=True)
```
Comment (rahulporuri) [inline chaco/base_contour_plot.py:60]: If the cache valid flags arent transient, then the caches themselves should also be transient - `_levels` and `_colors`.

I would think `HasTraits` would ignore traits that are private i.e. that start an `_`. If that isn't the case, there are a lot more private traits that we will want to mark as transient.

Comment (aaronayres35) [reply chaco/base_contour_plot.py:60]: As you suggested, I printed `state` inside the `ArrayDataSource.__getstate__` method on master and ran the test suite.  I do see `_` prefixed traits, eg `_data`, '_min_index', etc.  So it looks like these need to be addressed

Comment (aaronayres35) [reply chaco/base_contour_plot.py:60]: >If that isn't the case, there are a lot more private traits that we will want to mark as transient.

Does this mean all private traits be transient?

Comment (rahulporuri) [reply chaco/base_contour_plot.py:60]: > As you suggested, I printed state inside the ArrayDataSource.__getstate__ method on master and ran the test suite. I do see _ prefixed traits, eg _data, '_min_index', etc. So it looks like these need to be addressed

Sigh. I was afraid of that.

> Does this mean all private traits be transient?

Let's not do that. Definitely not in this PR.

Comment (rahulporuri) [reply chaco/base_contour_plot.py:60]: So, I imagine the code will recreate the cache if a `*cache*` is `False`, which it is by default because we're marking it as a transient. So, I think we can ignore all of the traits that are recalculated based on the `*cache*` flag. - i.e. nothing actionable in this PR.

File: chaco/contour_line_plot.py [hunk 8]
```diff
@@ -46,16 +46,16 @@ class ContourLinePlot(BaseContourPlot):
...
     # Is the cached width data valid?
-    _widths_cache_valid = Bool(False)
+    _widths_cache_valid = Bool(False, transient=True)
 
     # Is the cached style data valid?
-    _styles_cache_valid = Bool(False)
+    _styles_cache_valid = Bool(False, transient=True)
 
     # Cached list of line widths
     _widths = List
```
Comment (rahulporuri) [inline chaco/contour_line_plot.py:61]: looks like this is technically a cache but like I said earlier, this will be ignored/recomputed because the `_widths_cache_valid` trait is `False` - no action required, just pointing it out.

File: chaco/tools/simple_zoom.py [hunk 9]
```diff
@@ -38,13 +38,23 @@ class SimpleZoom(AbstractOverlay, ToolHistoryMixin, BaseZoomTool):
...
 
+<<<<<<< HEAD
+    # Is the tool always "on"? If True, left-clicking always initiates
+    # a zoom operation; if False, the user must press a key to enter zoom mode.
+    always_on = Bool(False, transient=True)
+
+    # Defines a meta-key, that works with always_on to set the zoom mode. This
+    # is useful when the zoom tool is used in conjunction with the pan tool.
+    always_on_modifier = Enum(None, "shift", "control", "alt", transient=True)
+=======
```
Comment (rahulporuri) [inline chaco/tools/simple_zoom.py:49]: looks like a merge conflict crept in - and the chaco testsuite sadly didnt capture this!

File: chaco/tools/simple_zoom.py [hunk 10]
```diff
@@ -68,27 +78,48 @@ class SimpleZoom(AbstractOverlay, ToolHistoryMixin, BaseZoomTool):
     #: Conversion ratio from wheel steps to zoom factors.
     wheel_zoom_step = Float(1.0)
 
+<<<<<<< HEAD
```
Comment (rahulporuri) [inline chaco/tools/simple_zoom.py:81]: another merge conflict

Comment (rahulporuri) [reply chaco/tools/simple_zoom.py:81]: looks like there are a few more in this module

Comment (aaronayres35) [reply chaco/tools/simple_zoom.py:81]: Oh yikes! 😓 thank you for catching these!

File: chaco/tools/simple_zoom.py [hunk 11]
```diff
@@ -38,23 +38,13 @@ class SimpleZoom(AbstractOverlay, ToolHistoryMixin, BaseZoomTool):
     #:   Perform a "box" selection on two axes.
     tool_mode = Enum("box", "range")
 
-<<<<<<< HEAD
     # Is the tool always "on"? If True, left-clicking always initiates
     # a zoom operation; if False, the user must press a key to enter zoom mode.
```
Comment (rahulporuri) [inline chaco/tools/simple_zoom.py]: looks like you lost the `#:` because of the merge conflicts.

**Review by rahulporuri — APPROVED** [review]
LGTM
